clean:
  (): better_id3.commands.CleanCommand
  directory: "D:\\Aymeric\\Musique"
  clean_items:
    - (): better_id3.clean.FileNameBlacklist
      read_only: true
      blacklist: "AlbumArtSmall\\.jpg|AlbumArt_.*\\.jpg|Folder\\.jpg|Thumbs\\.db|desktop\\.ini|\\.DS_Store|\\._"
    - (): better_id3.clean.EachDirectoryShouldHaveACover
      read_only: true
      allowed:
        - "cover.jpg"
        - "Cover.jpg"
        - "front.jpg"

logging:
  version: 1
  disable_existing_loggers: false
  handlers:
    default:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
      level: INFO
    colored:
      class: logging.StreamHandler
      formatter: colored
      stream: ext://sys.stdout
      level: INFO
  formatters:
    standard:
      format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    colored:
      (): colorlog.ColoredFormatter
      fmt: "%(log_color)s%(asctime)s - %(levelname)-8s - %(name)s: %(message)s%(reset)s"
  loggers:
    '':
      handlers:
        - colored
      level: DEBUG
      propagate: False
