logging: !import logging.yml

clean:
  (): better_id3.commands.CleanCommand
  directory: "D:\\Aymeric\\Musique"
  clean_items:
    - (): better_id3.clean.FileNameBlacklist
      read_only: true
      blacklist: "AlbumArtSmall\\.jpg|AlbumArt_.*\\.jpg|Folder\\.jpg|Thumbs\\.db|desktop\\.ini|\\.DS_Store|\\._"
    - (): better_id3.clean.EachDirectoryShouldHaveACover
      read_only: true
      allowed:
        - "cover.jpg"
        - "Cover.jpg"
        - "front.jpg"
