version: 1
disable_existing_loggers: false
handlers:
  default:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout
    level: DEBUG
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
loggers:
  '':
    handlers:
      - default
    level: INFO
    propagate: False
